-- Generated by Oracle SQL Developer Data Modeler 21.1.0.092.1221
--   at:        2021-06-08 19:12:49 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Author (
    author VARCHAR2(255) NOT NULL
);

create table authorTable( 
    author VARCHAR2(20) not NULL
);
drop table authorTable;


ALTER TABLE authorTable ADD CONSTRAINT authorTable_pk PRIMARY KEY ( author );

CREATE TABLE book (
    isbn        INTEGER NOT NULL,
    title       VARCHAR2(255) NOT NULL,
    language    VARCHAR2(255) NOT NULL,
    quantity    VARCHAR2 (255) NOT NULL,
--  ERROR: Datatype UNKNOWN is not allowed 
     
    member_id   INTEGER NOT NULL,
    issuedate   DATE NOT NULL,
    returndate  DATE NOT NULL
);

ALTER TABLE book ADD CONSTRAINT book_pk PRIMARY KEY ( isbn );

CREATE TABLE category (
    id    INTEGER NOT NULL,
    Cname  VARCHAR2(255) NOT NULL
);

ALTER TABLE bcategory ADD CONSTRAINT bcategory_pk PRIMARY KEY ( id );

CREATE TABLE emplogin (
    password     VARCHAR2(255) NOT NULL,
    employee_id  INTEGER NOT NULL
);

CREATE UNIQUE INDEX emplogin__idx ON
    emplogin (
        employee_id
    ASC );

CREATE TABLE Lemployee (
    id       INTEGER NOT NULL,
    fname    VARCHAR2(255) NOT NULL,
    lname    VARCHAR2(255) NOT NULL,
    contact  VARCHAR2(255) NOT NULL,
    address  VARCHAR2(255)
--  ERROR: VARCHAR2 size not specified 
     NOT NULL
);

ALTER TABLE Lemployee ADD CONSTRAINT Lemployee_pk PRIMARY KEY ( id );
insert into employee(id,fname, lname, contact, address) values(1,"abc","abc","abc","abc");

CREATE TABLE faculty (
    id          INTEGER NOT NULL,
    fid_1       INTEGER NOT NULL,
    department  VARCHAR2 (255)
--  ERROR: VARCHAR2 size not specified 
     NOT NULL
);

ALTER TABLE faculty ADD CONSTRAINT faculty_pk PRIMARY KEY ( id );

ALTER TABLE UniFaculty ADD CONSTRAINT faculty_pkv1 UNIQUE ( fid_1 );

CREATE TABLE fine (
    amount     INTEGER NOT NULL,
    member_id  INTEGER NOT NULL
);

CREATE TABLE has_author (
    book_isbn          INTEGER NOT NULL,
    author_authorname  VARCHAR2 (255) NOT NULL
);

ALTER TABLE has_author ADD CONSTRAINT has_author_pk PRIMARY KEY ( book_isbn,
                                                                  author_authorname );

CREATE TABLE haspublisher (
    book_isbn       INTEGER NOT NULL,
    publisher  VARCHAR2(255) NOT NULL
);

ALTER TABLE haspublisher ADD CONSTRAINT haspublisher_pk PRIMARY KEY ( book_isbn,
                                                                      publisher_name );

CREATE TABLE history (
    title       VARCHAR2(255) NOT NULL,
    issuedate   DATE NOT NULL,
    returndate  DATE NOT NULL,
    member_id   INTEGER NOT NULL
);

CREATE UNIQUE INDEX history__idx ON
    history (
        member_id
    ASC );

CREATE TABLE member (
    id               INTEGER NOT NULL,
    fname            VARCHAR2(255),
    lname            VARCHAR2(255) NOT NULL,
    email            VARCHAR2(255) NOT NULL,
    contact_address  VARCHAR2(255) NOT NULL,
    address          VARCHAR2(255) NOT NULL
);

ALTER TABLE member ADD CONSTRAINT member_pk PRIMARY KEY ( id );

CREATE TABLE mlogin (
    password   VARCHAR2(255) NOT NULL,
    member_id  INTEGER NOT NULL
);

CREATE UNIQUE INDEX mlogin__idx ON
    mlogin (
        member_id
    ASC );
select * from news;

CREATE TABLE news (
    id    INTEGER NOT NULL,
    text  VARCHAR2(255) NOT NULL
);

ALTER TABLE news ADD CONSTRAINT news_pk PRIMARY KEY ( id );
select * from publisher;
CREATE TABLE publisher (
    name VARCHAR2(255) NOT NULL
);

ALTER TABLE publisher ADD CONSTRAINT publisher_pk PRIMARY KEY ( name );

CREATE TABLE roles (
    role         VARCHAR2(255) NOT NULL,
    employee_id  INTEGER NOT NULL
);

CREATE TABLE student (
    id        INTEGER NOT NULL,
    rnum      INTEGER NOT NULL,
    degree    VARCHAR2(255) NOT NULL,
    semester  VARCHAR2(10) NOT NULL
);

ALTER TABLE student ADD CONSTRAINT student_pk PRIMARY KEY ( id );

ALTER TABLE student ADD CONSTRAINT student_pkv1 UNIQUE ( rnum );

ALTER TABLE book
    ADD CONSTRAINT book_member_fk FOREIGN KEY ( member_id )
        REFERENCES member ( id );

ALTER TABLE emplogin
    ADD CONSTRAINT emplogin_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( id );

ALTER TABLE faculty
    ADD CONSTRAINT faculty_member_fk FOREIGN KEY ( id )
        REFERENCES member ( id );

ALTER TABLE fine
    ADD CONSTRAINT fine_member_fk FOREIGN KEY ( member_id )
        REFERENCES member ( id );

ALTER TABLE has_author
    ADD CONSTRAINT has_author_author_fk FOREIGN KEY ( author_authorname )
        REFERENCES author ( authorname );

ALTER TABLE has_author
    ADD CONSTRAINT has_author_book_fk FOREIGN KEY ( book_isbn )
        REFERENCES book ( isbn );

ALTER TABLE haspublisher
    ADD CONSTRAINT haspublisher_book_fk FOREIGN KEY ( book_isbn )
        REFERENCES book ( isbn );

ALTER TABLE haspublisher
    ADD CONSTRAINT haspublisher_publisher_fk FOREIGN KEY ( publisher_name )
        REFERENCES publisher ( name );
select * from employee;
ALTER TABLE history
    ADD CONSTRAINT history_member_fk FOREIGN KEY ( member_id )
        REFERENCES member ( id );

ALTER TABLE mlogin
    ADD CONSTRAINT mlogin_member_fk FOREIGN KEY ( member_id )
        REFERENCES member ( id );

ALTER TABLE roles
    ADD CONSTRAINT roles_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( id );

ALTER TABLE student
    ADD CONSTRAINT student_member_fk FOREIGN KEY ( id )
        REFERENCES member ( id );

--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             3
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   5
-- WARNINGS                                 0


select * from fine;

commit;
